
export enum ItemRarity {
  EPICKI = 'EPICKI',
  LEGENDARNY_DOSKONALY = 'LEGENDARNY_DOSKONALY',
  LEGENDARNY_DOBRY = 'LEGENDARNY_DOBRY',
  LEGENDARNY = 'LEGENDARNY',
  DOSKONALY = 'DOSKONALY',
  DOBRY = 'DOBRY',
  ZWYKLY = 'ZWYKLY'
}
