// AUTO-GENERATED by scripts/generate-feature-flags.js — do not edit by hand.
// Regenerated on every build/serve from env vars (see that script for details).
export const FEATURE_FLAGS = {
  ekspedycjaEnabled: true
};
